version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.20

build_image: &build_image
  docker:
    - image: cimg/node:16.14.0

attach_workspace: &attach_workspace
  attach_workspace:
    at: .

persist_build_to_workspace: &persist_build_to_workspace
  persist_to_workspace:
    root: .
    paths:
      - build

persist_node_modules_to_workspace: &persist_node_modules_to_workspace
  persist_to_workspace:
    root: .
    paths:
      - node_modules


jobs:
  install:
    <<: *build_image
    steps:
      - checkout
      - restore_cache:
          keys:
            - nodejs-deps-{{ checksum "package-lock.lock" }}
            - nodejs-deps-
      - run: |
          npm install
      - save_cache:
          paths:
            - node_modules
          key: nodejs-deps-{{ checksum "package-lock.lock" }}
      - <<: *persist_node_modules_to_workspace



workflows:
  version: 2
  main:
    jobs:
      - install:
          filters:
            branches:
              only:
                - deployments/development
                - deployments/staging
                - deployments/production

      # - build:
      #     requires:
      #       - install
      #     filters:
      #       branches:
      #         only:
      #           - development
      #           - staging
      #           - production
      # - development:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only: development
      # - staging:
      #     requires:
      #       - build
      #   filters:
      #     branches:
      #       only: staging
      # - production:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only: production
